name: Release
run-name: Release ${{ inputs.varsion }} 
   
on:
  workflow_dispatch:
    inputs:
      varsion:
        description: 'Version in X.X.X format'
        required: true
        type: string
  
jobs:
  release:
    name: Dreft Release   
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup Amazon.Lambda.Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build Lambda Package 
      working-directory: ./Butler.Bot.AWS
      run: dotnet lambda package

    - name: Create Release
      id: release
      uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         tag_name: v${{ inputs.varsion }} 
         release_name: v${{ inputs.varsion }} 
         draft: true


